GET http://127.0.0.1:8000/setup/testuser@example.com/testpassword
Accept: application/json

###

GET http://127.0.0.1:8000/getbot/testuser@example.com
Accept: application/json

###

GET http://127.0.0.1:8000/dump/
Accept: application/json

###

GET http://127.0.0.1:8000/ik_leef/testuser@example.com
Accept: application/json

###

GET http://127.0.0.1:8000/cleanup/
accept: application/json